### ISSUE TITLE
GRC: Add support for types

### ISSUE THREAD

**Issue by frankosterfeld** [fair-acc/graph-prototype#266]
Right now gr::load_grc() instantiates all blocks `Block<T>` as `Block<double>`. Add support for other types (and multiple template parameters) to load_grc/save_grc.

**Comment by RalphSteinhagen** [comment]
As discussed during our meeting this morning, the existing gr plugin system can already register at least template parameters, for example, `T` and `U` as shown [here](https://github.com/fair-acc/graph-prototype/blob/86e88f6af586349083b23535f18c365d889ce8ed/core/test/plugins/good_conversion_plugin.cpp#L29). 

```cpp
auto registerConvert = gr::registerBlock<good::convert, gr::BlockParameters<double, float>, gr::BlockParameters<float, double>>(grPluginInstance());
```
This should equally work for the other variants. We agreed that, for now, the potential other template parameters and NTTP will be absorbed into the named type KISS.

I had a look at how these types are encoded in the grc YAML files, and it seems that there the `T` and `U` are part of the parameter definitions and mapped to `T: complex` (I guess for the output), and `type complex` for the inputs. We should follow that convention. See the following GRC saved-file snippet for example:

```yaml
options:
  parameters:
    author: ''
    catch_exceptions: 'True'
    category: '[GRC Hier Blocks]'
    cmake_opt: ''
    comment: ''
    copyright: ''
    description: ''
    gen_cmake: 'On'
    gen_linking: dynamic
    generate_options: qt_gui
    hier_block_src_path: '.:'
    id: test
    max_nouts: '0'
    output_language: python
    placement: (0,0)
    qt_qss_theme: ''
    realtime_scheduling: ''
    run: 'True'
    run_command: '{python} -u {filename}'
    run_options: prompt
    sizing_mode: fixed
    thread_safe_setters: ''
    title: Not titled yet
    window_size: (1000,1000)
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [8, 8]
    rotation: 0
    state: enabled

blocks:
- name: samp_rate
  id: variable
  parameters:
    comment: ''
    value: '32000'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [184, 12]
    rotation: 0
    state: enabled
- name: analog_sig_source_0
  id: analog_sig_source
  parameters:
    T: complex
    affinity: ''
    alias: ''
    ampl: '1.0'
    comment: ''
    frequency: '1000'
    impl: cpu
    maxoutbuf: '0'
    minoutbuf: '0'
    offset: '0'
    phase: '0'
    sampling_freq: samp_rate
    showports: 'False'
    waveform: analog.waveform_t.CONSTANT
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [224, 300.0]
    rotation: 0
    state: enabled
- name: blocks_complex_to_float_0
  id: blocks_complex_to_float
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [672, 184.0]
    rotation: 0
    state: enabled
- name: blocks_complex_to_mag_0
  id: blocks_complex_to_mag
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [680, 352.0]
    rotation: 0
    state: enabled
- name: blocks_float_to_char_0
  id: blocks_float_to_char
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    scale: '1'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [824, 236.0]
    rotation: 0
    state: enabled
- name: blocks_null_sink_0
  id: blocks_null_sink
  parameters:
    affinity: ''
    alias: ''
    bus_structure_sink: '[[0,],]'
    comment: ''
    num_inputs: '1'
    type: float
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [856, 352.0]
    rotation: 0
    state: enabled
- name: blocks_null_sink_0_0
  id: blocks_null_sink
  parameters:
    affinity: ''
    alias: ''
    bus_structure_sink: '[[0,],]'
    comment: ''
    num_inputs: '1'
    type: float
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [944, 176.0]
    rotation: 0
    state: enabled
- name: blocks_null_sink_0_0_0
  id: blocks_null_sink
  parameters:
    affinity: ''
    alias: ''
    bus_structure_sink: '[[0,],]'
    comment: ''
    num_inputs: '1'
    type: byte
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [1008, 248.0]
    rotation: 0
    state: enabled
- name: blocks_null_sink_1
  id: blocks_null_sink
  parameters:
    affinity: ''
    alias: ''
    bus_structure_sink: '[[0,],]'
    comment: ''
    num_inputs: '1'
    type: complex
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [624, 512.0]
    rotation: 0
    state: enabled
- name: blocks_null_source_0
  id: blocks_null_source
  parameters:
    affinity: ''
    alias: ''
    bus_structure_source: '[[0,],]'
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    num_outputs: '1'
    type: complex
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [352, 504.0]
    rotation: 0
    state: enabled
- name: math_multiply_const_0
  id: math_multiply_const
  parameters:
    T: complex
    affinity: ''
    alias: ''
    comment: ''
    impl: cpu
    k: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    showports: 'False'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [456, 332.0]
    rotation: 0
    state: enabled

connections:
- [analog_sig_source_0, '0', math_multiply_const_0, '0']
- [blocks_complex_to_float_0, '0', blocks_null_sink_0_0, '0']
- [blocks_complex_to_float_0, '1', blocks_float_to_char_0, '0']
- [blocks_complex_to_mag_0, '0', blocks_null_sink_0, '0']
- [blocks_float_to_char_0, '0', blocks_null_sink_0_0_0, '0']
- [blocks_null_source_0, '0', blocks_null_sink_1, '0']
- [math_multiply_const_0, '0', blocks_complex_to_float_0, '0']
- [math_multiply_const_0, '0', blocks_complex_to_mag_0, '0']

metadata:
  file_format: 1
  grc_version: 3.10.9.2
```

@frankosterfeld does the above info make this issue obsolete? Could we close this issue in favour of the other one?

The small remainder could be implemented as part of: https://github.com/fair-acc/opendigitizer/issues/181.
